services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/supportflux_db
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: